<template>
  <header class="bar">
    <div class="bar-left">
      <span class="logo">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2">
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
          <polyline points="14 2 14 8 20 8"/>
          <line x1="16" y1="13" x2="8" y2="13"/>
          <line x1="16" y1="17" x2="8" y2="17"/>
          <polyline points="10 9 9 9 8 9"/>
        </svg>
      </span>
      <span class="app-name">CVModifire</span>
    </div>

    <div class="bar-center">
      <div class="filename-wrap">
        <svg class="file-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
          <polyline points="14 2 14 8 20 8"/>
        </svg>
        <input
          class="filename-input"
          :value="filename"
          @input="$emit('update:filename', $event.target.value)"
          spellcheck="false"
          placeholder="NomFichier.pdf"
        />
        <span v-if="isAutoGenerated" class="auto-badge">auto</span>
      </div>
    </div>

    <div class="bar-right">
      <button class="btn-icon" @click="$emit('settings')" title="Paramètres (clé API)">
        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="12" cy="12" r="3"/>
          <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/>
        </svg>
      </button>
      <button class="btn-preview" @click="$emit('preview')">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
          <circle cx="12" cy="12" r="3"/>
        </svg>
        Aperçu
      </button>
      <button class="btn-export" @click="$emit('export')" :disabled="exporting">
        <svg v-if="!exporting" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
          <polyline points="7 10 12 15 17 10"/>
          <line x1="12" y1="15" x2="12" y2="3"/>
        </svg>
        <svg v-else class="spin" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M21 12a9 9 0 1 1-6.219-8.56"/>
        </svg>
        {{ exporting ? 'Export...' : 'Exporter PDF' }}
      </button>
    </div>
  </header>
</template>

<script setup>
defineProps({
  filename: String,
  isAutoGenerated: Boolean,
  exporting: Boolean,
})
defineEmits(['update:filename', 'export', 'preview', 'settings'])
</script>

<style scoped>
.bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  padding: 0 20px;
  height: 52px;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  flex-shrink: 0;
  z-index: 10;
}

.bar-left {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 150px;
}

.logo {
  display: flex;
  align-items: center;
  color: var(--primary);
}

.app-name {
  font-weight: 700;
  font-size: 15px;
  letter-spacing: -0.3px;
  color: var(--text);
}

.bar-center {
  flex: 1;
  display: flex;
  justify-content: center;
}

.filename-wrap {
  display: flex;
  align-items: center;
  gap: 6px;
  background: var(--surface-2);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 0 10px;
  height: 34px;
  min-width: 280px;
  max-width: 480px;
  width: 100%;
  transition: border-color 0.15s;
}

.filename-wrap:focus-within {
  border-color: var(--primary);
  background: var(--surface);
}

.file-icon { color: var(--text-3); flex-shrink: 0; }

.filename-input {
  flex: 1;
  border: none;
  background: transparent;
  font-size: 13px;
  font-weight: 500;
  color: var(--text);
  min-width: 0;
}

.filename-input::placeholder { color: var(--text-3); }

.auto-badge {
  font-size: 10px;
  font-weight: 600;
  background: var(--primary-light);
  color: var(--primary);
  padding: 2px 6px;
  border-radius: 4px;
  flex-shrink: 0;
}

.bar-right {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 150px;
  justify-content: flex-end;
}

.btn-preview {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 0 14px;
  height: 34px;
  background: var(--surface-2);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  color: var(--text-2);
  font-size: 13px;
  font-weight: 500;
  transition: all 0.15s;
}

.btn-preview:hover {
  background: var(--surface);
  border-color: var(--border-hover);
  color: var(--text);
}

.btn-export {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 0 16px;
  height: 34px;
  background: var(--primary);
  border-radius: var(--radius);
  color: white;
  font-size: 13px;
  font-weight: 600;
  transition: background 0.15s;
}

.btn-export:hover:not(:disabled) { background: var(--primary-hover); }
.btn-export:disabled { opacity: 0.6; cursor: not-allowed; }

.btn-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 34px;
  height: 34px;
  background: var(--surface-2);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  color: var(--text-3);
  cursor: pointer;
  transition: all 0.15s;
}
.btn-icon:hover { background: var(--surface); color: var(--text-2); border-color: var(--border-hover); }

.spin {
  animation: spin 0.8s linear infinite;
}
@keyframes spin { to { transform: rotate(360deg); } }
</style>
