<template>
  <FilenameBar
    v-model:filename="filename"
    :is-auto-generated="isAutoGenerated"
    :exporting="exporting"
    @export="exportPdf"
    @preview="showPreview = true"
  />

  <div class="workspace">
    <!-- Job Panel -->
    <div class="pane pane-job">
      <JobPanel v-model="jobText" />
    </div>

    <div class="divider" />

    <!-- Resume Editor -->
    <div class="pane pane-editor">
      <ResumeEditor :resume="resume" :job-keywords="jobAnalysis.keywords" />
    </div>
  </div>

  <!-- Preview modal -->
  <Teleport to="body">
    <ResumePreview
      v-if="showPreview"
      :resume="resume"
      :modal="true"
      @close="showPreview = false"
    />
  </Teleport>

  <!-- Hidden PDF render target -->
  <ResumePreview ref="previewRef" :resume="resume" />

  <!-- Toast -->
  <Teleport to="body">
    <div v-if="toast" class="toast" :class="toast.type">
      <svg v-if="toast.type === 'success'" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
        <polyline points="20 6 9 17 4 12"/>
      </svg>
      <svg v-else width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="12" cy="12" r="10"/>
        <line x1="12" y1="8" x2="12" y2="12"/>
        <line x1="12" y1="16" x2="12.01" y2="16"/>
      </svg>
      {{ toast.message }}
    </div>
  </Teleport>
</template>

<script setup>
import { ref, reactive, computed, watch, onMounted } from 'vue'
import FilenameBar from './components/FilenameBar.vue'
import JobPanel from './components/JobPanel.vue'
import ResumeEditor from './components/ResumeEditor.vue'
import ResumePreview from './components/ResumePreview.vue'
import { analyzeJob, generateFilename } from './utils/keywords.js'
import { loadResume, saveResume, defaultResume } from './utils/storage.js'

// --- State ---
const jobText = ref('')
const showPreview = ref(false)
const exporting = ref(false)
const previewRef = ref(null)
const toast = ref(null)

const resume = reactive(loadResume() || defaultResume())

// Auto-save
watch(resume, () => saveResume(resume), { deep: true })

// Job analysis
const jobAnalysis = computed(() => analyzeJob(jobText.value))

// Filename
const autoFilename = computed(() =>
  generateFilename(
    jobAnalysis.value.contractType,
    jobAnalysis.value.role,
    resume.personal.firstName,
    resume.personal.lastName
  )
)

const manualFilename = ref('')
const isAutoGenerated = ref(true)

const filename = computed({
  get() {
    return isAutoGenerated.value ? autoFilename.value : manualFilename.value
  },
  set(val) {
    manualFilename.value = val
    isAutoGenerated.value = val === autoFilename.value || val === ''
    if (val === '') isAutoGenerated.value = true
  }
})

watch(autoFilename, (val) => {
  if (isAutoGenerated.value) manualFilename.value = val
})

// --- PDF Export ---
async function exportPdf() {
  if (exporting.value) return
  exporting.value = true

  try {
    const html2pdf = (await import('html2pdf.js')).default
    const el = previewRef.value?.pdfRef

    if (!el) {
      showToast('Erreur : élément introuvable', 'error')
      return
    }

    const fname = filename.value || 'CV.pdf'

    await html2pdf()
      .set({
        margin: 0,
        filename: fname,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: {
          scale: 2,
          useCORS: true,
          letterRendering: true,
        },
        jsPDF: {
          unit: 'mm',
          format: 'a4',
          orientation: 'portrait',
        },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
      })
      .from(el)
      .save()

    showToast(`Exporté : ${fname}`, 'success')
  } catch (err) {
    console.error(err)
    showToast('Erreur lors de l\'export', 'error')
  } finally {
    exporting.value = false
  }
}

function showToast(message, type = 'success') {
  toast.value = { message, type }
  setTimeout(() => { toast.value = null }, 3500)
}
</script>

<style scoped>
.workspace {
  display: flex;
  flex: 1;
  overflow: hidden;
  min-height: 0;
}

.pane {
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background: var(--surface);
}

.pane-job {
  width: 38%;
  min-width: 280px;
}

.pane-editor {
  flex: 1;
  min-width: 0;
}

.divider {
  width: 1px;
  background: var(--border);
  flex-shrink: 0;
}

.toast {
  position: fixed;
  bottom: 24px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 18px;
  border-radius: var(--radius-lg);
  font-size: 13px;
  font-weight: 500;
  box-shadow: var(--shadow-lg);
  z-index: 999;
  animation: slideUp 0.2s ease;
}

.toast.success {
  background: #166534;
  color: white;
}

.toast.error {
  background: #991b1b;
  color: white;
}

@keyframes slideUp {
  from { opacity: 0; transform: translateX(-50%) translateY(8px); }
  to   { opacity: 1; transform: translateX(-50%) translateY(0); }
}
</style>
