<template>
  <FilenameBar
    v-model:filename="filename"
    :is-auto-generated="isAutoGenerated"
    :exporting="exporting"
    @export="exportPdf"
    @preview="showPreview = true"
    @settings="showSettings = true"
  />

  <div class="workspace">
    <div class="pane pane-job">
      <JobPanel
        v-model="jobText"
        :user-skills="allUserSkills"
        @add-skill="addSkillFromJob"
        @adapt="adaptToJob"
      />
    </div>

    <div class="divider" />

    <div class="pane pane-editor">
      <ResumeEditor
        :resume="resume"
        :job-keywords="jobAnalysis.keywords"
        :has-api-key="!!apiKey"
        :rewrite-loading="rewriteLoading"
        @rewrite-summary="rewriteSummary"
      />
    </div>
  </div>

  <!-- Modals -->
  <Teleport to="body">
    <ResumePreview v-if="showPreview" :resume="resume" :modal="true" @close="showPreview = false" />
    <SettingsPanel v-if="showSettings" v-model="apiKey" @close="showSettings = false" />
  </Teleport>

  <!-- Hidden PDF render target -->
  <ResumePreview ref="previewRef" :resume="resume" />

  <!-- Toast -->
  <Teleport to="body">
    <div v-if="toast" class="toast" :class="toast.type">
      <svg v-if="toast.type === 'success'" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
        <polyline points="20 6 9 17 4 12"/>
      </svg>
      <svg v-else width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="12" cy="12" r="10"/>
        <line x1="12" y1="8" x2="12" y2="12"/>
        <line x1="12" y1="16" x2="12.01" y2="16"/>
      </svg>
      {{ toast.message }}
    </div>
  </Teleport>
</template>

<script setup>
import { ref, reactive, computed, watch } from 'vue'
import FilenameBar    from './components/FilenameBar.vue'
import JobPanel       from './components/JobPanel.vue'
import ResumeEditor   from './components/ResumeEditor.vue'
import ResumePreview  from './components/ResumePreview.vue'
import SettingsPanel  from './components/SettingsPanel.vue'
import { analyzeJob, generateFilename, skillMatchesKeyword } from './utils/keywords.js'
import { loadResume, saveResume, defaultResume } from './utils/storage.js'

// ── Core state ──────────────────────────────────────────────────
const jobText      = ref('')
const showPreview  = ref(false)
const showSettings = ref(false)
const exporting    = ref(false)
const rewriteLoading = ref(false)
const previewRef   = ref(null)
const toast        = ref(null)

const resume = reactive(loadResume() || defaultResume())
watch(resume, () => saveResume(resume), { deep: true })

// API key (localStorage, never sent anywhere except Anthropic)
const apiKey = ref(localStorage.getItem('cvmodifire_apikey') || '')
watch(apiKey, val => localStorage.setItem('cvmodifire_apikey', val))

// ── Job analysis ────────────────────────────────────────────────
const jobAnalysis = computed(() => analyzeJob(jobText.value))

const allUserSkills = computed(() =>
  Object.values(resume.skills || {}).flat()
)

// ── Filename ────────────────────────────────────────────────────
const autoFilename = computed(() =>
  generateFilename(
    jobAnalysis.value.contractType,
    jobAnalysis.value.role,
    resume.personal.firstName,
    resume.personal.lastName
  )
)

const manualFilename  = ref('')
const isAutoGenerated = ref(true)

const filename = computed({
  get() { return isAutoGenerated.value ? autoFilename.value : manualFilename.value },
  set(val) {
    manualFilename.value = val
    isAutoGenerated.value = !val || val === autoFilename.value
  }
})
watch(autoFilename, val => { if (isAutoGenerated.value) manualFilename.value = val })

// ── Add skill from job gap ───────────────────────────────────────
const SKILL_CAT = {
  sql: 'databases', postgresql: 'databases', mysql: 'databases', mongodb: 'databases',
  redis: 'databases', oracle: 'databases', sqlite: 'databases', elasticsearch: 'databases',
  docker: 'devops', kubernetes: 'devops', terraform: 'devops', ansible: 'devops',
  jenkins: 'devops', 'gitlab ci': 'devops', 'github actions': 'devops', 'ci/cd': 'devops',
  nginx: 'devops', linux: 'devops', iis: 'devops', vps: 'devops', helm: 'devops',
  aws: 'cloud', azure: 'cloud', gcp: 'cloud', vercel: 'cloud', ovhcloud: 'cloud',
  python: 'scripting', bash: 'scripting', powershell: 'scripting',
  jest: 'tests', cypress: 'tests', postman: 'tests', selenium: 'tests', jmeter: 'tests',
  react: 'frontend', 'react.js': 'frontend', vue: 'frontend', 'vue.js': 'frontend',
  angular: 'frontend', 'next.js': 'frontend', nuxt: 'frontend', html: 'frontend', css: 'frontend',
  'node.js': 'backend', express: 'backend', nestjs: 'backend', django: 'backend',
  'spring boot': 'backend', laravel: 'backend', '.net': 'backend', adonisjs: 'backend',
  agile: 'methods', agilité: 'methods', scrum: 'methods', tdd: 'methods', bdd: 'methods',
}

function addSkillFromJob(kw) {
  if (!resume.skills) resume.skills = {}
  const cat = SKILL_CAT[kw.toLowerCase()] || 'other'
  if (!resume.skills[cat]) resume.skills[cat] = []
  if (!resume.skills[cat].includes(kw)) {
    resume.skills[cat].push(kw)
    showToast(`"${kw}" ajouté aux compétences`, 'success')
  }
}

// ── ADAPT TO JOB ─────────────────────────────────────────────────
const ROLE_TITLES = {
  DevOps:       'Ingénieur DevOps',
  FullStack:    'Développeur Full Stack',
  Frontend:     'Développeur Frontend',
  Backend:      'Développeur Backend',
  Support:      'Technicien Support Logiciel',
  DataEngineer: 'Data Engineer',
  DataScientist:'Data Scientist / ML Engineer',
  Mobile:       'Développeur Mobile',
  Cybersecurity:'Ingénieur Cybersécurité',
  CloudEngineer:'Ingénieur Cloud',
  Dev:          'Développeur Logiciel',
}

function adaptToJob() {
  const { role, keywords } = jobAnalysis.value

  if (!role && !keywords.length) {
    showToast("Collez d'abord une offre d'emploi", 'error')
    return
  }

  const changes = []

  // 1. Update personal title
  if (role && ROLE_TITLES[role]) {
    resume.personal.title = ROLE_TITLES[role]
    changes.push(`titre → ${ROLE_TITLES[role]}`)
  }

  // 2. Auto-hide skills not matching any job keyword
  if (keywords.length > 0) {
    const cats = ['frontend','backend','databases','devops','tests','cloud','scripting','methods']
    if (!resume.hiddenSkills) resume.hiddenSkills = {}
    let hidden = 0
    cats.forEach(cat => {
      const skills = resume.skills?.[cat] || []
      const toHide = skills.filter(s => !keywords.some(kw => skillMatchesKeyword(s, kw)))
      resume.hiddenSkills[cat] = toHide
      hidden += toHide.length
    })
    if (hidden > 0) changes.push(`${hidden} compétence${hidden > 1 ? 's' : ''} masquée${hidden > 1 ? 's' : ''}`)
  }

  // 3. Sort experiences by keyword relevance score
  if (keywords.length > 0) {
    const scored = resume.experiences.map(exp => {
      const text = `${exp.position} ${exp.company} ${exp.bullets}`.toLowerCase()
      const score = keywords.reduce((acc, kw) => acc + (text.includes(kw.toLowerCase()) ? 1 : 0), 0)
      return { exp, score }
    })
    scored.sort((a, b) => b.score - a.score)
    resume.experiences.splice(0, resume.experiences.length, ...scored.map(({ exp }) => exp))
    changes.push('expériences triées')
  }

  showToast(
    changes.length
      ? `CV adapté : ${changes.join(' · ')} ✓`
      : 'Aucun changement nécessaire',
    'success'
  )
}

// ── REWRITE SUMMARY WITH CLAUDE ──────────────────────────────────
async function rewriteSummary() {
  if (!apiKey.value) {
    showSettings.value = true
    showToast('Configurez votre clé API Anthropic ⚙️', 'error')
    return
  }
  if (!jobText.value.trim()) {
    showToast("Collez d'abord une offre d'emploi", 'error')
    return
  }

  rewriteLoading.value = true

  try {
    const eduStr  = resume.education.filter(e => e.school).slice(0, 2)
      .map(e => `${e.degree}${e.period ? ` (${e.period})` : ''} à ${e.school}`).join(', ')
    const expStr  = resume.experiences.filter(e => e.company).slice(0, 3)
      .map(e => `${e.position} chez ${e.company} (${e.period})`).join(' | ')
    const skillStr = Object.values(resume.skills || {}).flat().slice(0, 20).join(', ')
    const contract = jobAnalysis.value.contractType || 'poste'

    const prompt = `Tu es expert en rédaction de CV pour des candidatures tech en France.

Réécris l'accroche de ce CV pour qu'elle corresponde parfaitement à cette offre.

**Profil :**
- Candidat : ${resume.personal.firstName} ${resume.personal.lastName}
- Formation : ${eduStr}
- Compétences clés : ${skillStr}
- Expériences : ${expStr}

**Accroche actuelle :**
${resume.summary}

**Offre d'emploi :**
${jobText.value.slice(0, 2500)}

**Instructions :**
- Exactement 2 paragraphes courts en français, séparés par une ligne vide
- Mentionne le type de contrat (${contract}) et le poste ciblé
- Adapte les compétences mises en avant au poste spécifique
- Garde les vraies informations (école, formation, expérience)
- Ton professionnel et dynamique
- UNIQUEMENT les 2 paragraphes, sans titre ni commentaire`

    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey.value,
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 600,
        messages: [{ role: 'user', content: prompt }],
      }),
    })

    if (!res.ok) {
      const err = await res.json().catch(() => ({}))
      throw new Error(err.error?.message || `Erreur HTTP ${res.status}`)
    }

    const data = await res.json()
    const text = data.content?.[0]?.text?.trim()

    if (text) {
      resume.summary = text
      showToast('Accroche réécrite par Claude ✓', 'success')
    }
  } catch (err) {
    showToast('Erreur : ' + err.message, 'error')
  } finally {
    rewriteLoading.value = false
  }
}

// ── PDF EXPORT ──────────────────────────────────────────────────
async function exportPdf() {
  if (exporting.value) return
  exporting.value = true
  try {
    const html2pdf = (await import('html2pdf.js')).default
    const el = previewRef.value?.pdfRef
    if (!el) { showToast('Erreur : élément introuvable', 'error'); return }

    const fname = filename.value || 'CV.pdf'
    await html2pdf()
      .set({
        margin: 0,
        filename: fname,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, letterRendering: true },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
      })
      .from(el)
      .save()
    showToast(`Exporté : ${fname}`, 'success')
  } catch (err) {
    console.error(err)
    showToast("Erreur lors de l'export", 'error')
  } finally {
    exporting.value = false
  }
}

// ── Toast ───────────────────────────────────────────────────────
function showToast(message, type = 'success') {
  toast.value = { message, type }
  setTimeout(() => { toast.value = null }, 3500)
}
</script>

<style scoped>
.workspace {
  display: flex;
  flex: 1;
  overflow: hidden;
  min-height: 0;
}

.pane {
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background: var(--surface);
}

.pane-job    { width: 38%; min-width: 280px; }
.pane-editor { flex: 1; min-width: 0; }

.divider {
  width: 1px;
  background: var(--border);
  flex-shrink: 0;
}

.toast {
  position: fixed;
  bottom: 24px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 18px;
  border-radius: var(--radius-lg);
  font-size: 13px;
  font-weight: 500;
  box-shadow: var(--shadow-lg);
  z-index: 999;
  animation: slideUp 0.2s ease;
  white-space: nowrap;
}

.toast.success { background: #166534; color: white; }
.toast.error   { background: #991b1b; color: white; }

@keyframes slideUp {
  from { opacity: 0; transform: translateX(-50%) translateY(8px); }
  to   { opacity: 1; transform: translateX(-50%) translateY(0); }
}
</style>
